apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-despachos
  labels:
    app: db-despachos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-despachos
  template:
    metadata:
      labels:
        app: db-despachos
    spec:
      nodeSelector:
        role: db
      containers:
      - name: db-despachos
        image: 066442453610.dkr.ecr.us-east-1.amazonaws.com/ep3-db-despachos:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "myrootpassword"
        - name: MYSQL_DATABASE
          value: "despachos_db"
        - name: MYSQL_USER
          value: "myuser"
        - name: MYSQL_PASSWORD
          value: "mypassword"
        - name: MYSQL_ROOT_HOST
          value: "%"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "250m"
            memory: "512Mi"
