name: Despliegue de Capa de Backend

on:
  push:
    branches: [ "deploy" ]
    paths:
      - "back-Ventas_SpringBoot/**"
      - "back-Despachos_SpringBoot/**"
      - ".github/workflows/deploy-backend.yml"
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: cluster-proyecto-ep3

jobs:
  build-push-deploy:
    name: Construir, Subir y Desplegar Backends en EKS
    runs-on: ubuntu-latest
    steps:
    - name: Descargar Código
      uses: actions/checkout@v4

    - name: Configurar Credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Iniciar Sesión en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Construir y Subir Imágenes
      run: |
        REGISTRY=${{ steps.login-ecr.outputs.registry }}
        
        # Build y Push Ventas
        docker build -t $REGISTRY/ep3-back-ventas:latest ./back-Ventas_SpringBoot/Springboot-API-REST
        docker push $REGISTRY/ep3-back-ventas:latest
        
        # Build y Push Despachos
        docker build -t $REGISTRY/ep3-back-despachos:latest ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
        docker push $REGISTRY/ep3-back-despachos:latest

    - name: Configurar Acceso a EKS
      run: |
        aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

    - name: Desplegar Backends en EKS
      run: |
        kubectl rollout restart deployment/back-ventas
        kubectl rollout restart deployment/back-despachos
