name: Despliegue de Capa de Base de Datos

on:
  push:
    branches: [ "deploy" ]
    paths:
      - "init-db/**"
      - ".github/workflows/deploy-database.yml"
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: cluster-proyecto-ep3

jobs:
  build-push-deploy-db:
    name: Construir, Subir y Desplegar DBs en EKS
    runs-on: ubuntu-latest
    steps:
    - name: Descargar Código
      uses: actions/checkout@v4

    - name: Configurar Credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Iniciar Sesión en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Construir y Subir Imágenes de DB
      run: |
        REGISTRY=${{ steps.login-ecr.outputs.registry }}
        
        # Build y Push DB Ventas
        docker build -f ./init-db/Dockerfile.ventas -t $REGISTRY/ep3-db-ventas:latest ./init-db
        docker push $REGISTRY/ep3-db-ventas:latest
        
        # Build y Push DB Despachos
        docker build -f ./init-db/Dockerfile.despachos -t $REGISTRY/ep3-db-despachos:latest ./init-db
        docker push $REGISTRY/ep3-db-despachos:latest

    - name: Configurar Acceso a EKS
      run: |
        aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

    - name: Desplegar Bases de Datos en EKS
      run: |
        kubectl rollout restart deployment/db-ventas
        kubectl rollout restart deployment/db-despachos
